export const industryOptions = [
  "Information Technology",
  "Finance",
  "Healthcare",
  "Manufacturing",
  "Retail",
  "Education",
  "Construction",
  "Hospitality",
  "Transportation",
  "Energy",
  "Telecommunications",
  "Agriculture",
  "Professional Services",
  "Real Estate",
  "Other",
];

export const intervalOptions = ["monthly", "yearly"];

export const voices = {
  "ar-XA": [
    "ar-XA-Standard-A",
    "ar-XA-Standard-B",
    "ar-XA-Standard-C",
    "ar-XA-Standard-D",
  ],
  "ar-SA": ["ar-SA-Wavenet-A", "ar-SA-Standard-A"],
  "en-US": [
    "en-US-Wavenet-A",
    "en-US-Wavenet-B",
    "en-US-Wavenet-C",
    "en-US-Wavenet-D",
    "en-US-Wavenet-E",
    "en-US-Wavenet-F",
    "en-US-Standard-A",
    "en-US-Standard-B",
    "en-US-Standard-C",
    "en-US-Standard-D",
    "en-US-Standard-E",
    "en-US-Standard-F",
    "en-US-Neural2-A",
    "en-US-Neural2-C",
    "en-US-Neural2-D",
    "en-US-Neural2-E",
    "en-US-Studio-B",
    "en-US-Studio-C",
  ],
  "en-GB": [
    "en-GB-Wavenet-A",
    "en-GB-Wavenet-B",
    "en-GB-Wavenet-C",
    "en-GB-Wavenet-D",
    "en-GB-Standard-A",
    "en-GB-Standard-B",
    "en-GB-Standard-C",
    "en-GB-Standard-D",
  ],
  "en-IN": ["en-IN-Wavenet-A", "en-IN-Standard-A"],
  "en-AU": [
    "en-AU-Wavenet-A",
    "en-AU-Wavenet-B",
    "en-AU-Wavenet-C",
    "en-AU-Wavenet-D",
    "en-AU-Standard-A",
    "en-AU-Standard-B",
    "en-AU-Standard-C",
    "en-AU-Standard-D",
  ],
  "en-KE": ["en-KE-Standard-A"],
  "en-TZ": ["en-TZ-Standard-A"],
  "en-NG": ["en-NG-Standard-A"],
  "en-ZA": ["en-ZA-Standard-A"],
  "en-PH": ["en-PH-Standard-A", "en-PH-Wavenet-A"],
  "en-IE": ["en-IE-Standard-A", "en-IE-Wavenet-A"],
};
